CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  joined TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  name VARCHAR(255) UNIQUE,
  gamerid VARCHAR(255) UNIQUE,
  email VARCHAR(255) UNIQUE,
  password VARCHAR(255),
  avatar VARCHAR(255),
  level INTEGER DEFAULT 100,
  enabled INTEGER DEFAULT 1,
  banned INTEGER DEFAULT 0
);